services:
  - type: web
    name: production
    runtime: docker
    repo: https://github.com/keVookanansi/church
    envVars:
      - fromGroup: kanisa
    region: frankfurt
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
